//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class classicmodelsEntities : DbContext
    {
        public classicmodelsEntities()
            : base("name=classicmodelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<offices> offices { get; set; }
        public virtual DbSet<orderdetails> orderdetails { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<productlines> productlines { get; set; }
        public virtual DbSet<products> products { get; set; }
    }
}
